.\" Man page for decode.
.\" Simon Ever-Hale - Fall 2014

.TH decode 1 "November 29, 2011" "CSCI 241" "Oberlin College"

.SH NAME
.B decode
\- A program to decode Huffman-encoded files.

.SH SYNOPSIS
.B decode
<filename>

.SH DESCRIPTION
Decodes a file which has been compressed with Huffman encoding and prints the original text to stdin.

.SH OPTIONS
.IP "<filename>"
The file which will be decoded.

.SH AUTHOR
Simon Ever-Hale (Fall 2014)
