.\" Man page for encode.
.\" Simon Ever-Hale - Fall 2014

.TH encode 1 "November 29, 2011" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
\- A program to compress files.

.SH SYNOPSIS
.B encode
<filename>

.SH DESCRIPTION
Encodes the file specified in the first command-line arguments using Huffman encoding and prints the results to stdin.

.SH OPTIONS
.IP "<filename>"
The file which will be encoded.

.SH AUTHOR
Simon Ever-Hale (Fall 2014)
